### ISSUE TITLE
Deprecation T3 V8 LTS

### ISSUE THREAD

**Issue by p1ngb4ck** [codesource/typo3-cdsrc_bepwreset#1]
EXT:cdsrc_bepwreset/Classes/Utility/ExtensionManagerConfigurationUtility.php:CDSRC\CdsrcBepwreset\Utility\ExtensionManagerConfigurationUtility->renderBackendGroupSelect" has been deprecated in TYPO3 v8 when calling GeneralUtility::callUserFunction(), make sure the class is available via the class loader.

TYPO3\CMS\Backend\Utility\BackendUtility::getRecordsByField() - since TYPO3 v8, will be removed in TYPO3 v9

.. could anybody please update this extension not to throw any deprecations any more, please ? thanks in advance !

**Comment by codesource** [comment]
Thanks for report. I will upload the new version to TER

**Comment by p1ngb4ck** [comment]
Thanks soo much =))
This is what I call great support !
