### ISSUE TITLE
Less verbose messages?

### ISSUE THREAD

**Issue by ochorocho** [codesource/typo3-cdsrc_bepwreset#19]
This is not a big thing, but this tells potential attackers to keep going because this user exists.
Maybe shift detailed messages to the typo3 logs or only show these detailes messages in development context ?

https://github.com/codesource/typo3-cdsrc_bepwreset/blob/1d52a4fbd28df577ede55e68620d2849ac23d27e/Classes/Tool/ResetTool.php#L355

Thanks.

**Comment by codesource** [comment]
Good point, I will see if that not already the case.

**Comment by ochorocho** [comment]
Thanks for taking care :-)
