### ISSUE TITLE
Password forgotten + reset at next login not working on TYPO3 8.7.8

### ISSUE THREAD

**Issue by JulienHenchoz** [codesource/typo3-cdsrc_bepwreset#2]
Hi,
I just installed the dev-master version on my TYPO3 8.7.8, and found that nor the forgotten password process nor the force reset worked in my case.
In both cases, I got a success message saying that my password was changed and that I could login, but nothing was actually updated in DB. Password stayed the same, and the tx_cdsrcbepwreset_resetAtNextLogin flag stayed to 1.

By digging into the code, I found that the DataHandler built it's "excludedTablesAndFields" list inside the $tce->start called in typo3conf/ext/cdsrc_bepwreset/Classes/Tool/ResetTool.php at line 214.
Given this, the $tce->admin = 1 ran right after the start() call has no effect : the excluded tables list is already set and silently refuses to update any of my fields.

I managed to fix this by adding the following line right before the call to $tce->start() : 
`        
$GLOBALS['BE_USER']->user['admin'] = 1;
`

Am I the only one who had this issue ?

**Comment by codesource** [comment]
Not tested yet on last TYPO3. I will check this

**Comment by codesource** [comment]
I have checked with a fresh install. 
By default "password" and extension field do not have "exclude" option, it means that they are not affected by "excludedTablesAndFields".
https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Configuration/TCA/be_users.php

But your remark is pertinent, I need to check if it doesn't have any border effect to put "$tce->admin" before "$tce->start".

Do you have any extension installed that modify TCA for be_users?
