### ISSUE TITLE
Plain text password

### ISSUE THREAD

**Issue by mikestreety** [codesource/typo3-cdsrc_bepwreset#22]
Hi,

Have just upgraded my site to TYPO3 9.5 and decided to try and install this plugin. Install and managed to reset password, but fail to login after reset. 

Looked in the databased and notice it is storing my new password as plain text - not using the recommended hash.

Is there a step I have missed (installed ext, ran database analyser)?

**Comment by codesource** [comment]
Done multiple test about that, I can't reproduce this bug.
I use TYPO3 datamapper to update field in database. Passwords are saved as TYPO3 do it in backend.
Please re-open it if you have still this bug.
