### ISSUE TITLE
Conflict with TYPO3 9.5.17

### ISSUE THREAD

**Issue by koehnlein** [codesource/typo3-cdsrc_bepwreset#23]
Hi everybody,

after installing latest TYPO3 security update 9.5.17, I could not login anymore. During debugging I found out, the password is not sent via POST to the backend. 

When I set `basic.enablePasswordResetFromLoginForm = false` in extension configuration (or directly in LocalConfiguration.php) the login again works as expected. Maybe there is any invalid HTML or JavaScript anywhere?

**Comment by codesource** [comment]
I will check this.

**Comment by koehnlein** [comment]
I think, it's related to these latest changes: https://github.com/TYPO3/TYPO3.CMS/commit/1b28fec3af40f085299af2a93adc38030365043c#diff-257c7449dd19de4d76a67d23914840ce

And I have the similar problem with 8.7.33 ELTS. But disabling `basic.enablePasswordResetFromLoginForm` did not help here, so I had to uninstall the complete extension.

I guess, the updates from Login.html should be integrated in `EXT:cdsrc_bepwreset/Resources/Private/Layouts/Login.html` - But I think, it should be checked if it breaks 9.5.16, 8.7.32 and 7.6.41.
