### ISSUE TITLE
Password reset e-mail translation

### ISSUE THREAD

**Issue by JulienHenchoz** [codesource/typo3-cdsrc_bepwreset#3]
It is currently not possible to translate the password reset email, since its PartialRootPath is hardcoded in the PHP in /typo3conf/ext/cdsrc_bepwreset/Classes/Tool/ResetTool.php line 91.

Would it be possible to move this configuration to TypoScript so it can be overriden and allow a custom e-mail template ?

**Comment by codesource** [comment]
TypoScript is used for Frontend and Backend configuration. 
This script run before anything else. 

What do you think about on using an hook instead of TypoScript?
